# Generated by Django 3.1.4 on 2020-12-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblMemberList',
            fields=[
                ('memb_no', models.AutoField(db_column='MEMB_NO', primary_key=True, serialize=False)),
                ('memb_id', models.CharField(db_column='MEMB_ID', max_length=100)),
                ('memb_gender', models.CharField(db_column='MEMB_GENDER', max_length=10)),
                ('password', models.CharField(db_column='PASSWORD', max_length=100)),
                ('add_date', models.DateTimeField(db_column='ADD_DATE')),
                ('memb_name', models.CharField(db_column='MEMB_NAME', max_length=100)),
            ],
            options={
                'db_table': 'TBL_MEMBER_LIST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNewsKeywordList',
            fields=[
                ('word_no', models.AutoField(db_column='WORD_NO', primary_key=True, serialize=False)),
                ('word_morpheme', models.CharField(blank=True, db_column='WORD_MORPHEME', max_length=500, null=True)),
                ('word_class', models.CharField(blank=True, db_column='WORD_CLASS', max_length=100, null=True)),
                ('positive_yn', models.CharField(blank=True, db_column='POSITIVE_YN', max_length=1, null=True)),
                ('negative_yn', models.CharField(blank=True, db_column='NEGATIVE_YN', max_length=1, null=True)),
            ],
            options={
                'db_table': 'TBL_NEWS_KEYWORD_LIST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNewsKeywordMap',
            fields=[
                ('map_no', models.AutoField(db_column='MAP_NO', primary_key=True, serialize=False)),
                ('word_origin', models.CharField(blank=True, db_column='WORD_ORIGIN', max_length=500, null=True)),
                ('word_morpheme', models.CharField(blank=True, db_column='WORD_MORPHEME', max_length=500, null=True)),
                ('news_no', models.IntegerField(blank=True, db_column='NEWS_NO', null=True)),
                ('word_count', models.IntegerField(blank=True, db_column='WORD_COUNT', null=True)),
            ],
            options={
                'db_table': 'TBL_NEWS_KEYWORD_MAP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTotalCarNewsList',
            fields=[
                ('news_no', models.AutoField(db_column='NEWS_NO', primary_key=True, serialize=False)),
                ('news_category', models.IntegerField(blank=True, db_column='NEWS_CATEGORY', null=True)),
                ('media_code', models.CharField(blank=True, db_column='MEDIA_CODE', max_length=50, null=True)),
                ('media_name', models.CharField(blank=True, db_column='MEDIA_NAME', max_length=100, null=True)),
                ('news_code', models.CharField(db_column='NEWS_CODE', max_length=100, unique=True)),
                ('news_title', models.CharField(blank=True, db_column='NEWS_TITLE', max_length=1000, null=True)),
                ('news_summary', models.TextField(blank=True, db_column='NEWS_SUMMARY', null=True)),
                ('news_content', models.TextField(blank=True, db_column='NEWS_CONTENT', null=True)),
                ('view_count', models.IntegerField(blank=True, db_column='VIEW_COUNT', null=True)),
                ('news_img_url', models.CharField(blank=True, db_column='NEWS_IMG_URL', max_length=1000, null=True)),
                ('news_url', models.CharField(blank=True, db_column='NEWS_URL', max_length=1000, null=True)),
                ('write_date', models.CharField(blank=True, db_column='WRITE_DATE', max_length=30, null=True)),
                ('add_date', models.DateTimeField(blank=True, db_column='ADD_DATE', null=True)),
                ('mining_status', models.CharField(blank=True, db_column='MINING_STATUS', max_length=10, null=True)),
            ],
            options={
                'db_table': 'TBL_TOTAL_CAR_NEWS_LIST',
                'managed': False,
            },
        ),
    ]
