# Generated by Django 3.1.4 on 2020-12-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201208_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblmemberlist',
            name='password',
            field=models.CharField(db_column='PASSWORD', max_length=100, verbose_name='비밀번호'),
        ),
    ]
