# Generated by Django 3.1.4 on 2020-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201208_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmemberlist',
            name='memb_name',
            field=models.CharField(db_column='MEMB_NAME', default='default', max_length=100, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
