# Generated by Django 3.1.4 on 2020-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_tblmemberlist_memb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmemberlist',
            name='logined_date',
            field=models.DateTimeField(db_column='LOGINED_DATE', default='2020-12-08 07:00:51', verbose_name='로그인일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblmemberlist',
            name='logouted_date',
            field=models.DateTimeField(db_column='LOGOUTED_DATE', default='2020-12-08 07:00:51', verbose_name='로그아웃일시'),
            preserve_default=False,
        ),
    ]
