# Generated by Django 3.1.4 on 2020-12-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201208_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblmemberlist',
            name='logined_date',
        ),
        migrations.RemoveField(
            model_name='tblmemberlist',
            name='logouted_date',
        ),
    ]
